### ISSUE TITLE
[Feature request] Support for Long (BigInt) numbers

### ISSUE THREAD

**Issue by clozanoruiz** [BdR76/CSVLint#10]
Hi,
Thanks for sharing this plugin - It has proven really useful several times.
Would it be possible for the plugin to detect long ints (or BigInts) when validating data?
For instance, when validating this sample csv data:
```
Col1;Col2;Col3
19097;170456;TEXT1
19097;18661704;TEXT2
16084;7405017000001464;TEXT3
```

It informs of an invalid value:
```
** error line 4: Column 2 value "7405017000001464" not a valid integer value
Inspected 4 lines, 1 data errors found, time elapsed 00:00:00.000
```

I know it is not a valid integer but it is a valid long integer though... Perhaps we could have an option in the plugin´s settings to set whether we work with ints ot bigints? Or just directly accept bigints...

Thanks.

**Comment by BdR76** [comment]
> It has proven really useful several times.

Thanks for the feedback and that's good to hear. Btw if I may ask which parts are most useful, the error checking (validate) or reformatting or some other feature?

> Would it be possible for the plugin to detect long ints (or BigInts) when validating data?

I ran into a similar related issue with numeric values with more than 12 decimals. I think I need to change the validating routine so that it will accept any number, no matter how many digits (or decimals), and then the only restriction is the WIDTH parameter.

I'll look into this issue when I have time

**Comment by clozanoruiz** [comment]
Hi,
certainly the **validating** is pretty useful. In my case mostly to check whether we mix strings and numbers in the same field. **Trim values** is also used, and finally **count unique values**.

Regarding the latter I miss a total of unique values in the 'data report':
```
[test.csv]
Col1,Col2,Col3
text,  #,c
text,abc,d
text,   ,d
text,cde,d
text,cde,a
````
schema.ini:
```
[test.csv]
Format=CSVDelimited
ColNameHeader=True
Col1=Col1 Text Width 4
Col2=Col2 Text Width 3
Col3=Col3 Text Width 1
```
It would be nice having a row for all the columns stating the number of total unique values (also for numbers), for instance:
<pre>
3: Col3
DataTypes      : string (5 = 100.0%)
Width range    : 1 characters
<b>Unique values  : 3</b>
</pre>

But can live without it :)

Ah! And adding foreground colours to the light theme has been a nice addition, just because the color of the cursor line could make difficult to differenciate columns when using background highlighting.

**Comment by BdR76** [comment]
By default, the unique values count is limited to maximum 15, because coded values typically will have around that many different values. It's limited because for the average user-case it's not that useful to just list all decimal and date values (like price or birthdate) and tracking all unique values also has a performance cost.

That's why it only displays unique values coded columns, like `-- Unique values (2) --` meaning 2 unique values, followed by the actual values.

```
6: Gender
DataTypes      : string (100000 = 100.0%)
Width range    : 4 ~ 6 characters
-- Unique values (2) --
n=49141        : Female
n=50859        : Male
```
But, you can go to `Plugins > CSV Lint > Settings` and set `UniqueValueMax` to like 999999999 (larger than the amount of lines in datafile). That way it will make the "Analyse data report" just list all unqiue values for every column, plus maybe a bit slower depending on the size of the datafile.

Btw if I can ask what type of data files are your working with (like generally; medical, finance, engineering, retail etc) that you want to detect unique values count for each column?

**Comment by clozanoruiz** [comment]
Apologies for the delay.
I meant to just show the total count, without enering in the individual counts for each value. For instance if I extract all the POIs (Points of Interest) in a region, and I think there should be, i.e., 30 of them (each with their numeric code), I would like to see in the file analysis that the column containing POIs has 30 unique values indeed - without listing every single unique value as I can use the 'unique values' feature for that...

But, I'm OK with the tool as it is. No complains, only gratitude :)

**Comment by BdR76** [comment]
Large integer values are now supported, see the `IntegerDigitsMax` setting. The default setting is 12 (because product barcodes are usually 13 characters) but you can change it to something like 20 and then auto-detect will correctly interpret values with 20 digits as integer values not text.

Also, validating integers and decimals is now only limited by the corresponding WIDTH for each column as set in the metadata.
