### ISSUE TITLE
[feature request] Option to disable/enable plugin

### ISSUE THREAD

**Issue by m-buecher** [BdR76/CSVLint#17]
Sometimes I load quite huge CSV files (200.000+ lines, 40+ columns) and do some searches and operations on them.
When CSVLint is installed then paging is heavily delayed, e.g. jumping to the end of one of those CSVs via CTRL+END takes over 85 seconds. While jumping to the start with CTRL+POS1 is done in 1 second.

For these cases I would like to temporary disable CSVLint to work faster on thoise CSVs.
Right now I have to remove the CSVLint plugin and reinstall it afterwards.
Having an option to disable it would make life more easier.

Thanks for your time
M. Bücher

**Comment by BdR76** [comment]
Thanks for letting me know, Which version of the plugin are you using (see menu `Plugins -> CSV Lint -> About`)? Because opening large files had a performance improvement in version 0.4.5. That is, the syntax rendering was set to an asynchronous background thread, so you can continue to use Notepad++ while it's rendering the column colors.

Secondly, the plugin automatically applies syntax highlighting to files with extension `.csv`. You can disable this but not from the menu. You can open the CSVLint.xml settings file (usually located at `%USERPROFILE%\AppData\Roaming\Notepad++\plugins\config\CSVLint.xml`) and change the `ext="csv"` to `ext=""` and then restart Notepad++.

Let me know if that helps.

**Comment by Fruchtzwerg94** [comment]
Hi @BdR76 ,
the ticket is already closed but I am asking this here anyway:
Is there a way to disable the plugin also for CSV files or / and activate it also for other files without adapting the configuration manually?
If not, it would be a great feature to enable / disable the plugin on the fly by button.

**Comment by Fruchtzwerg94** [comment]
I've added the feature in #42.

**Comment by BdR76** [comment]
Thanks for the PR but I'm not sure if an extra button is needed for this, it can be done from the menu as well. The gui is already quite cluttered as it is.

You can go to menu `Language -> CSV Lint` and `Language -> None` to toggle the CSV syntax highlighting on and off.

**Comment by Fruchtzwerg94** [comment]
Indeed you are right. But for me it seems more easy and straight forward to do this via the plugins GUI. Buts thats just my feeling.

**Comment by BdR76** [comment]
Ok I think I'll take this PR and change it to a small icon button on the right-hand side, because there's more room there.

Honestly, the gui window needs to be cleaned-up and rebuild at some point, but that requires a lot of time. 😅
