### ISSUE TITLE
Request: Sort by Column(s)

### ISSUE THREAD

**Issue by TeaEarlGrey** [BdR76/CSVLint#21]
Apologies in advance if entering a request as an "issue" is bad manners - I could not see anywhere else to do this. 
This is a really useful plug-in for quickly inspecting CSV files for issues (especially trailing zeros that excel always hides/ignores). 
It would be awesome if you could add the below to your to-do list...
* Sort by data by one or more Column(s)

Thanks!
TEG

**Comment by BdR76** [comment]
Thanks for the feedback, sorting is certainly a feature I want to add. But I want to do it by updating the "reformat data" more broadly, like move columns around, sort, and maybe even filter or join two datasets.

**Comment by BdR76** [comment]
The [latest release 0.4.6](https://github.com/BdR76/CSVLint/releases) has a new "Sort Data" feature, it can sort the data ascending or descending on a single column. It takes into account the data type, meaning it will sort datetime, integer and decimals on actual values instead of sorting alphabetically.

Although it can only sort on a single column, it's at least better than having no sorting option. See [the documentation](https://github.com/BdR76/CSVLint/tree/master/docs#sort-data) for a work-around by sorting multiple times.
