### ISSUE TITLE
It stops responding when I try to use reformatting

### ISSUE THREAD

**Issue by msfindik** [BdR76/CSVLint#30]
Hi,

It stops responding when I try to use reformatting, or split column. Highlighting works without a problem, then I go to CSV Lint window and still no problem, it shows the meta data and shows the errors in data, but when I click the errors, it again stops responding (the whole Np++) 

What makes me wonder is that every feature worked perfectly in my first tries. 30 mins later (or maybe when I close and reopen it) they started not working.

Thanks a lot,
Gustav

**Comment by msfindik** [comment]
Both NP++ and CSV Lint are latest version, convert data (mssql etc.) and generate metadata working perfectly without problems.

**Comment by BdR76** [comment]
Thanks for taking the time to post this issue. You say "latest version" is that v0.4.5.2? And do you mean the app freezes and stops responding? Or does it crash and show an "access violation" message or something?

I suspect it's due to the plug-in can't handle something specific in the data, so a use-case that wasn't anticipated in the code. Is it possible to send the data file to my e-mail address (see `About/Help` dialog)? If the data is too big or contains private/sensitive data, then maybe edit the data file to just include the lines that trigger the error and send that?

**Comment by BdR76** [comment]
It's difficult to do any meaningful trouble-shooting without version nr of NPP/plugin, debug info or an example file. If the problem still presists with the latest version then please open a new issue.
