### ISSUE TITLE
Option to change font?

### ISSUE THREAD

**Issue by Skrell** [BdR76/CSVLint#44]
Just wondering if it would be possible to give the user the option to change the front of the CSV Lint Window to something other than Courier?  Thanks!

**Comment by BdR76** [comment]
Is it the font-type or mostly the font size that is a problem currently? Or for example would you prefer it uses the same font as Notepad++ is using for the text file?

Btw it currently uses the Courier font because it's monospaced, which I figured is appropriate for the mostly technical logging and metadata texts.

**Comment by Skrell** [comment]
Both are an issue.  If you insist on hard coding it please consider using
the Microsoft font Consoles (which was designed to replace courier) and
making it smaller.  Thanks!

**Comment by BdR76** [comment]
I've added a new setting `Font` so you can adjust the font in the docked window, but it's just a string value for example `Consolas, 11pt`. It wil be available in the next version.

Btw unfortunately I couldn't add a font select dialog to one particular PropertyGrid cell

**Comment by Skrell** [comment]
Thank you!

**Comment by BdR76** [comment]
I was able to add the select font dialog the setting form, see latest release
