### ISSUE TITLE
Remove a column

### ISSUE THREAD

**Issue by amooefel** [BdR76/CSVLint#54]
Once the format of the file has been detected, you can add / split / search & replace by column, but I couldn't find an option to remove the column.  For columns with varying length text, or columns at the end of the lines, they don't line up well to use Notepad's Column Mode selection tool.  The Reformat --> Align Vertically, then a column select and delete is helpful for this, but it would be cleaner to have a simple option of just removing the column.

Thanks for a helpful tool!

**Comment by BdR76** [comment]
Thanks for posting the issue. CSV Lint is meant for quickly finding and fixing (relatively) small issues with CSV files, and not meant as an ETL tool. So for structural changes (add/remove/reorder columns) generally you're better off using a spreadsheet or Python script.

However, the "Add column" dialog already has a remove column checkbox, so I could add an radio option "Add column: do not add column" although that doesn't sound very intuitive. I'll see what I can do in the next version.

**Comment by BdR76** [comment]
I'ev just updated the New Column dialog so that you can right-click the radio buttons to deselect them. See commit https://github.com/BdR76/CSVLint/commit/a0fd0fc84be4c98e48b51042936e05264cf7a41f

You can now remove a column by checking the `Remove original column` checkbox and then deselecting the edit/split radio options. So it'll be a bit of a hidden feature, but I think it's better than adding a radio button with the label "Do not add column / Do nothing". It will be available in the next version, and you can download [the beta DLL here](https://github.com/BdR76/CSVLint/tree/master/CSVLintNppPlugin/bin) to try it out.

**Comment by BdR76** [comment]
The latest release v0.4.6.3 also includes this fix, and see [the documentation here](https://github.com/BdR76/CSVLint/tree/master/docs#remove-original-column), it will be automatically available in the next update of Notepad++

**Comment by djhenderson** [comment]
I spent way too much time trying to find this capability in the menu, options, and settings, and finally in the documentation.

Please add a bit of documentation that can, at the very least, be found by searching the readme file in the doc folder for either delete or remove so this capability is not hidden.

In my case, I wanted to remove an empty final column due to an extra trailing tab. I was able to work around this by trimming trailing white space. The disadvantage with this method is that all empty trailing columns no longer are counted as empty by the "Analyze data report".

BTW, thanks for building this plug-in.

**Comment by BdR76** [comment]
Thanks for posting about this, always good to hear feedback even when it's just about the (lack of) documentation 👍

You're right this was a hidden feature in the `Add column` dialog, but it's kind of obsolete now with the new `Select Columns` dialog, added in v4.7. With "Select Columns" you can simply "Select all" and then double-click in the "Selected columns" list to delete any unwanted columns. On top of that you can also reorder columns or select only the unique values, like a group-by function.

Anyway I've clarified the documentation and added the word "delete" so it's easier to search and find.
